apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupSync
metadata:
  name: github-group-sync
  namespace: group-sync-operator
spec:
  providers:
    - github:
        credentialsSecret:
          name: github-creds
          namespace: group-sync-operator
        organization: open-cluster-management
      name: github
  schedule: "0/30 * * * *"